global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nanoquant-api"
    static_configs:
      - targets: ["nanoquant-api:8000"]

  - job_name: "nanoquant-web"
    static_configs:
      - targets: ["nanoquant-web:8501"]

  - job_name: "ollama"
    static_configs:
      - targets: ["ollama:11434"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
